# Sửa lại thành đường dẫn này để Render có quyền ghi file
spring.datasource.url=jdbc:sqlite:/tmp/data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# Thêm dòng này để Hibernate tự tạo bảng nếu chưa có
spring.jpa.hibernate.ddl-auto=update



# 2. Cấu hình để Hibernate (Spring JPA) hoạt động với SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin

server.port=${PORT:8080}