# 1. Đường dẫn đến file SQLite của bạn (Dùng đường dẫn bạn đã dùng ở bài trước)
spring.datasource.url=jdbc:sqlite:C:/Users/congt/AppData/Roaming/DBeaverData/workspace6/.metadata/sample-database-sqlite-1/Chinook.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Cấu hình để Hibernate (Spring JPA) hoạt động với SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin

server.port=${PORT:8080}