# Thay thế dòng spring.datasource.url cũ bằng dòng này
spring.datasource.url=jdbc:sqlite:/opt/render/project/src/data.db
spring.datasource.driver-class-name=org.sqlite.JDBC


# 2. Cấu hình để Hibernate (Spring JPA) hoạt động với SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin

server.port=${PORT:8080}